apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tasks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # VULNERABILIDAD INTRODUCIDA: hostNetwork permite acceso a la red del host
      # KICS: "Host Network Access" - introducida
      hostNetwork: true
      # VULNERABILIDAD INTRODUCIDA: hostPID permite ver procesos del host
      # KICS: "Host PID Access" - introducida
      hostPID: true
      containers:
        - name: backend
          image: backend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          securityContext:
            # VULNERABILIDAD INTRODUCIDA: Contenedor con privilegios
            # KICS: "Container Is Privileged" - introducida
            privileged: true
            # VULNERABILIDAD INTRODUCIDA: Permite escalada de privilegios
            # KICS: "Container Allows Privilege Escalation" - introducida
            allowPrivilegeEscalation: true
            # VULNERABILIDAD INTRODUCIDA: Ejecuta como root
            # KICS: "Container Running As Root" - introducida
            runAsUser: 0