apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tasks-app
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: tasks
  DATABASE_URL: postgres://user:password@postgres-service:5432/tasks
